cc-base-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description
    >The Experiences custom object is designed to comprehensively track and manage all guest-related activities and services offered by the resort, such as recreational activities, golf outings, spa treatments, and other special events.</description>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <description
    >The Picture_URL__c field stores the web address (URL) of an image representing the experience, providing a visual reference for guests on different platforms and promotional materials.</description>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description
    >The Type field categorizes experiences into specific activities like &quot;Tennis &amp; Pickleball,&quot; &quot;Swimming Pools,&quot; and &quot;Beaches &amp; Snorkeling,&quot; helping guests easily find and book preferred activities, and aiding resort organization.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cc-employee-app/main/default/classes/ListExperiencesFromType.cls
public with sharing class ListExperiencesFromType {
    @InvocableMethod(
        label='List Experiences from Type'
        description='Returns a list of experiences based on their type'
    )
    public static List<ExperienceListWrapper> getExperiencesFromType(
        List<ExperienceTypeInput> experienceTypeInputs
    ) {
        List<ExperienceListWrapper> experienceWrappers = new List<ExperienceListWrapper>();
        for (ExperienceTypeInput experienceTypeInput : experienceTypeInputs) {
            // Get the experience type from the input
            String type =
                '%' +
                experienceTypeInput.type.toLowerCase().trim() +
                '%';
            // Fetch experiences records
            List<Experience__c> experiences = [
                SELECT Id, Name, Picture_URL__c
                FROM Experience__c
                WHERE Type__c LIKE :type
                WITH SYSTEM_MODE
            ];
            // Prepare the response
            ExperienceListWrapper experienceListWrapper = new ExperienceListWrapper();
            for (Experience__c experience : experiences) {
                experienceListWrapper.experiences.add(
                    new ExperienceItem(
                        experience.Name,
                        experience.Picture_URL__c,
                        'image/jpeg'
                    )
                );
            }
            experienceWrappers.add(experienceListWrapper);
        }
        return experienceWrappers;
    }

    public class ExperienceTypeInput {
        @InvocableVariable(
            label='Experience Type'
            description='The type of experience to list'
            required=true
        )
        public String type;
    }

    public class ExperienceListWrapper {
        @InvocableVariable(
            label='Experiences'
            description='The list of experiences of the given type'
        )
        public List<ExperienceItem> experiences;

        public ExperienceListWrapper() {
            this.experiences = new List<ExperienceItem>();
        }
    }

    public class ExperienceItem {
        public String name;
        public String imageUrl;
        public String mimeType;

        public ExperienceItem(String name, String imageUrl, String mimeType) {
            this.name = name;
            this.imageUrl = imageUrl;
            this.mimeType = mimeType;
        }
    }
}