cc-base-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description
    >The Experiences custom object is designed to comprehensively track and manage all guest-related activities and services offered by the resort, such as recreational activities, golf outings, spa treatments, and other special events.</description>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <description
    >Defines the maximum number of participants that can be accommodated in a single session of the experience, ensuring optimal guest enjoyment and safety.</description>
    <label>Capacity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description
    >Provides a detailed overview of the experience, including what guests can expect, any prerequisites or recommendations, and unique highlights that distinguish this activity or service.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <description
    >The Picture_URL__c field stores the web address (URL) of an image representing the experience, providing a visual reference for guests on different platforms and promotional materials.</description>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description
    >The Price__c field indicates the cost associated with participating in an experience, allowing guests to understand the financial commitment for each activity and enabling the resort to manage and display pricing information for its offerings.</description>
    <label>Price</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <description>The average Guest Rating</description>
    <formula>Sum_of_Guest_Reviews__c / Total_Guest_Reviews__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description
    >The Type field categorizes experiences into specific activities like &quot;Tennis &amp; Pickleball,&quot; &quot;Swimming Pools,&quot; and &quot;Beaches &amp; Snorkeling,&quot; helping guests easily find and book preferred activities, and aiding resort organization.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cc-base-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <description
    >The Session custom object tracks specific sessions of activities offered by the resort, detailing timing, location, and capacity, to manage bookings and optimize guest participation efficiently.</description>
    <label>Experience Session</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Session Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experience Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cc-base-app/main/default/objects/Session__c/fields/Booked_Slots__c.field-meta.xml
<CustomField>
    <fullName>Booked_Slots__c</fullName>
    <description
    >Tracks the number of slots already booked by guests for the experience, aiding in reservation management.</description>
    <label>Booked Slots</label>
    <summarizedField>Booking__c.Number_of_Guests__c</summarizedField>
    <summaryFilterItems>
        <field>Booking__c.Is_Canceled__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Booking__c.Session__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <formula>Experience__r.Capacity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description
    >Specifies the date on which the experience instance takes place, facilitating scheduling and planning for both the resort and the guests.</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description
    >Marks the concluding time of the experience instance, ensuring clear communication to guests about the duration of activities.</description>
    <formula
    >Start_Time__c + (Experience__r.Duration_Hours__c* 3600000)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >The parent experience that this object is scheduled based on.</description>
    <label>Experience</label>
    <referenceTo>Experience__c</referenceTo>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Percentage_Booked__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Booked__c</fullName>
    <description>The percentage of available slots.</description>
    <formula>Booked_Slots__c / Capacity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Percentage Booked</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

cc-base-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description
    >Indicates the beginning time of the experience instance, helping guests plan their day around scheduled activities.</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description
    >The Status field tracks the current state of an experience booking, indicating whether it is Confirmed, Canceled, or Completed. This field is essential for managing reservations effectively, allowing both resort staff and guests to understand the booking&apos;s progression from confirmation through completion or cancellation, facilitating clear communication and operational planning.</description>
    <formula
    >IF(Is_Canceled__c , &quot;Canceled&quot;, IF( Date__c &gt;= Today(), &quot;Confirmed&quot;, &quot;Completed&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

cc-base-app/main/default/classes/ExperienceController.cls
public with sharing class ExperienceController {
    @TestVisible
    private static Integer PAGE_SIZE = 9;

    /**
     * Endpoint that retrieves the sessions associated with an experience and a date
     * @param experienceId Experience ID
     * @param timestamp Timestamp representing the date on which the sessions take place
     * @return List of Session__c records
     */
    @AuraEnabled(cacheable=true scope='global')
    public static List<Session__c> getExperienceSessionsForDate(
        Id experienceId,
        Long timestamp
    ) {
        Date dateFilter = Datetime.newInstance(timestamp).date();
        List<Session__c> sessions = [
            SELECT
                Id,
                Booked_Slots__c,
                Capacity__c,
                End_Time__c,
                Percentage_Booked__c,
                Start_Time__c,
                Status__c,
                Experience__r.Price__c
            FROM Session__c
            WHERE Experience__c = :experienceId AND Date__c = :dateFilter
            WITH USER_MODE
            ORDER BY Start_Time__c ASC
            LIMIT 10
        ];
        return sessions;
    }

    /**
     * Retrieves experiences of a given type in a paginated format
     * @param type Experience type
     * @param pageNumber Page number. First page starts at 1.
     * @return Paginated set of experiences
     */
    @AuraEnabled(Cacheable=true scope='global')
    public static PagedResult getExperiences(String type, Integer pageNumber) {
        String whereClause = '';
        if (type != null || type != '') {
            whereClause = 'WHERE Type__c = :type';
        }
        Integer pageSize = ExperienceController.PAGE_SIZE;
        Integer offset = (pageNumber - 1) * pageSize;
        PagedResult result = new PagedResult();
        result.pageSize = pageSize;
        result.pageNumber = pageNumber;
        result.totalItemCount = Database.countQuery(
            'SELECT count() FROM Experience__c ' + whereClause
        );
        result.records = Database.query(
            'SELECT Id, Name, Description__c, Rating__c, Picture_URL__c FROM Experience__c ' +
                whereClause +
                ' WITH USER_MODE' +
                ' ORDER BY Name LIMIT :pageSize OFFSET :offset'
        );
        return result;
    }

    public with sharing class PagedResult {
        @AuraEnabled
        public Integer pageSize { get; set; }

        @AuraEnabled
        public Integer pageNumber { get; set; }

        @AuraEnabled
        public Integer totalItemCount { get; set; }

        @AuraEnabled
        public SObject[] records { get; set; }
    }
}