cc-base-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description
    >The Experiences custom object is designed to comprehensively track and manage all guest-related activities and services offered by the resort, such as recreational activities, golf outings, spa treatments, and other special events.</description>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description
    >The Type field categorizes experiences into specific activities like &quot;Tennis &amp; Pickleball,&quot; &quot;Swimming Pools,&quot; and &quot;Beaches &amp; Snorkeling,&quot; helping guests easily find and book preferred activities, and aiding resort organization.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/actions/ListExperienceTypes.cls
public with sharing class ListExperienceTypes {
    @InvocableMethod(
        label='List Experience Types'
        description='Returns a list of all available experience types'
    )
    public static List<ActionOutput> getExperienceTypes(
        List<ActionInput> inputs
    ) {
        // Get picklist values
        Schema.DescribeFieldResult fieldResult = Experience__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();

        // Prepare the type list
        List<String> experienceTypes = new List<String>();
        for (Schema.PicklistEntry entry : picklistValues) {
            if (entry.isActive()) {
                experienceTypes.add(entry.getLabel());
            }
        }

        ActionOutput output = new ActionOutput();
        output.experienceTypes = JSON.serialize(experienceTypes);
        // Prepare the responses
        List<ActionOutput> outputs = new List<ActionOutput>();
        for (ActionInput input : inputs) {
            outputs.add(output);
        }
        return outputs;
    }

    public class ActionOutput {
        @InvocableVariable(
            label='Experience Types'
            description='The list of available experience types'
        )
        public String experienceTypes;
    }

    public class ActionInput {
        /*
         * This input is not used, but it is required to make the method invocable.
         */
        @InvocableVariable(
            label='Unused dummy input'
            description='This input is not used, but it is required to make the method invocable.'
        )
        public String dummyInput;
    }
}