cc-base-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description
    >The Experiences custom object is designed to comprehensively track and manage all guest-related activities and services offered by the resort, such as recreational activities, golf outings, spa treatments, and other special events.</description>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description
    >The Type field categorizes experiences into specific activities like &quot;Tennis &amp; Pickleball,&quot; &quot;Swimming Pools,&quot; and &quot;Beaches &amp; Snorkeling,&quot; helping guests easily find and book preferred activities, and aiding resort organization.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cc-employee-app/main/default/classes/ListExperienceTypes.cls
public with sharing class ListExperienceTypes {
    @InvocableMethod(
        label='List Experience Types'
        description='Returns a list of all available experience types'
    )
    public static List<ExperienceTypeOutput> getExperienceTypes(
        List<ExperienceTypeInput> inputs
    ) {
        // Get picklist values
        Schema.DescribeFieldResult fieldResult = Experience__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();

        // Prepare the type list
        ExperienceTypeOutput typeList = new ExperienceTypeOutput();
        for (Schema.PicklistEntry entry : picklistValues) {
            if (entry.isActive()) {
                typeList.experienceTypes.add(
                    new ExperienceTypeItem(entry.getLabel())
                );
            }
        }

        // Prepare the responses
        List<ExperienceTypeOutput> typeOutput = new List<ExperienceTypeOutput>();
        for (ExperienceTypeInput input : inputs) {
            typeOutput.add(typeList);
        }
        return typeOutput;
    }

    public class ExperienceTypeOutput {
        @InvocableVariable(
            label='Experience Types'
            description='The list of available experience types'
        )
        public List<ExperienceTypeItem> experienceTypes;

        public ExperienceTypeOutput() {
            this.experienceTypes = new List<ExperienceTypeItem>();
        }
    }

    public class ExperienceTypeInput {
        /*
         * This input is not used, but it is required to make the method invocable.
         */
        @InvocableVariable(
            label='Unused dummy input'
            description='This input is not used, but it is required to make the method invocable.'
        )
        public String dummyInput;
    }

    public class ExperienceTypeItem {
        public String itemName;

        public ExperienceTypeItem(String itemName) {
            this.itemName = itemName;
        }
    }
}