cc-base-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description
    >The Experiences custom object is designed to comprehensively track and manage all guest-related activities and services offered by the resort, such as recreational activities, golf outings, spa treatments, and other special events.</description>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description
    >Provides a detailed overview of the experience, including what guests can expect, any prerequisites or recommendations, and unique highlights that distinguish this activity or service.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <description
    >The Picture_URL__c field stores the web address (URL) of an image representing the experience, providing a visual reference for guests on different platforms and promotional materials.</description>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description
    >The Type field categorizes experiences into specific activities like &quot;Tennis &amp; Pickleball,&quot; &quot;Swimming Pools,&quot; and &quot;Beaches &amp; Snorkeling,&quot; helping guests easily find and book preferred activities, and aiding resort organization.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/actions/ListExperiencesFromType.cls
public with sharing class ListExperiencesFromType {
    @InvocableMethod(
        label='List Experiences from Type'
        description='Returns a list of experiences based on their type'
    )
    public static List<ActionOutput> getExperiencesFromType(
        List<ActionInput> inputs
    ) {
        List<ActionOutput> outputs = new List<ActionOutput>();
        for (ActionInput input : inputs) {
            // Get the experience type from the input
            String type = '%' + input.experienceType.toLowerCase().trim() + '%';
            // Fetch experiences records
            List<Experience__c> experiences = [
                SELECT Id, Name, Picture_URL__c, Description__c
                FROM Experience__c
                WHERE Type__c LIKE :type
                WITH SYSTEM_MODE
            ];
            // Prepare the response
            ActionOutput output = new ActionOutput();
            output.experiences = JSON.serialize(experiences);
            outputs.add(output);
        }
        return outputs;
    }

    public class ActionInput {
        @InvocableVariable(
            label='Experience Type'
            description='The type of experience to list'
            required=true
        )
        public String experienceType;
    }

    public class ActionOutput {
        @InvocableVariable(
            label='Experiences'
            description='The list of experiences of the given type'
        )
        public String experiences;
    }
}