force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description
    >The Booking custom object manages reservations for guest activities, linking guests to their chosen experiences and tracking details like booking status and guest information, enabling efficient occupancy and capacity management.</description>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{00000000}</displayFormat>
        <label>Booking Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Activity_Level__c.field-meta.xml
<CustomField>
    <fullName>Activity_Level__c</fullName>
    <description
    >Describes the physical or engagement level required for the experience, such as &quot;Low&quot;, &quot;Medium&quot;, or &quot;High&quot;.</description>
    <formula>TEXT(Session__r.Experience__r.Activity_Level__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Activity Level</label>
    <type>Text</type>
</CustomField>

cc-base-app/main/default/objects/Booking__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description
    >The date of the booked experience, aiding in schedule planning.</description>
    <formula>Session__r.Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date</label>
    <type>Date</type>
</CustomField>

cc-base-app/main/default/objects/Booking__c/fields/Number_of_Guests__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Guests__c</fullName>
    <description
    >Specifies how many guests are included in the booking, ensuring appropriate accommodation.</description>
    <label>Number of Guests</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <description
    >Connects the booking to a specific session of an activity, detailing when and where it occurs.</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cc-base-app/main/default/objects/Booking__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description
    >The starting time of the experience, helping guests plan their day.</description>
    <formula>Session__r.Start_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

cc-base-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description
    >The Experiences custom object is designed to comprehensively track and manage all guest-related activities and services offered by the resort, such as recreational activities, golf outings, spa treatments, and other special events.</description>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Activity_Level__c.field-meta.xml
<CustomField>
    <fullName>Activity_Level__c</fullName>
    <description
    >Categorizes the experience based on its physical intensity or required skill level, with values ranging from &quot;Low&quot; for relaxed activities to &quot;High&quot; for more vigorous or skill-intensive experiences.</description>
    <label>Activity Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <description
    >Defines the maximum number of participants that can be accommodated in a single session of the experience, ensuring optimal guest enjoyment and safety.</description>
    <label>Capacity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Default_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Default_Start_Time__c</fullName>
    <description
    >The default start time used to build the schedule each day</description>
    <label>Default Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description
    >Provides a detailed overview of the experience, including what guests can expect, any prerequisites or recommendations, and unique highlights that distinguish this activity or service.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Duration_Hours__c.field-meta.xml
<CustomField>
    <fullName>Duration_Hours__c</fullName>
    <description
    >Indicates the length of time in hours that the experience is expected to last. This information helps guests plan their schedules and enables the resort to efficiently manage bookings and availability.</description>
    <label>Duration (Hours)</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description
    >Specifies the physical location or venue within the resort where the experience takes place, aiding guests in navigation and planning.</description>
    <label>Location</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <description
    >The Picture_URL__c field stores the web address (URL) of an image representing the experience, providing a visual reference for guests on different platforms and promotional materials.</description>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description
    >The Price__c field indicates the cost associated with participating in an experience, allowing guests to understand the financial commitment for each activity and enabling the resort to manage and display pricing information for its offerings.</description>
    <label>Price</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description
    >The Type field categorizes experiences into specific activities like &quot;Tennis &amp; Pickleball,&quot; &quot;Swimming Pools,&quot; and &quot;Beaches &amp; Snorkeling,&quot; helping guests easily find and book preferred activities, and aiding resort organization.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cc-base-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <description
    >The Session custom object tracks specific sessions of activities offered by the resort, detailing timing, location, and capacity, to manage bookings and optimize guest participation efficiently.</description>
    <label>Experience Session</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Session Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experience Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <formula>Experience__r.Capacity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description
    >Specifies the date on which the experience instance takes place, facilitating scheduling and planning for both the resort and the guests.</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Duration_Hours__c.field-meta.xml
<CustomField>
    <fullName>Duration_Hours__c</fullName>
    <formula>Experience__r.Duration_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration (Hours)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >The parent experience that this object is scheduled based on.</description>
    <label>Experience</label>
    <referenceTo>Experience__c</referenceTo>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>Experience__r.Location__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

cc-base-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description
    >Indicates the beginning time of the experience instance, helping guests plan their day around scheduled activities.</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/setup/classes/SampleDataTest.cls
@isTest
private class SampleDataTest {
    private static final Decimal SESSION_CAPACITY = 100;

    @isTest
    static void generateData_works() {
        List<Contact> contacts = getMockContacts(20);
        insert contacts;
        List<Experience__c> experiences = getMockExperiences(1);
        insert experiences;
        List<Session__c> initialSessions = getMockSessions(experiences, 1);
        insert initialSessions;

        Test.startTest();
        SampleDataGenerator.generateData();
        Test.stopTest();

        // Check that previous session was removed
        Assert.areEqual(
            0,
            [SELECT Id FROM Session__c WHERE Id = :initialSessions[0].Id].size()
        );
        // Check for the right amount of new sessions
        List<Session__c> sessions = [SELECT Date__c FROM Session__c];
        Assert.isTrue(sessions.size() > 0, 'Expected some new sessions');
        // Check that the right amout of days are covered
        Set<Date> daysCovered = new Set<Date>();
        for (Session__c session : sessions) {
            daysCovered.add(session.Date__c);
        }
        Assert.areEqual(
            SampleDataGenerator.PAST_DAYS_COVERED +
            SampleDataGenerator.FUTURE_DAYS_COVERED,
            daysCovered.size(),
            'Expected sessions to cover all days'
        );
    }

    @isTest
    static void generateData_fails_when_base_data_is_missing() {
        Test.startTest();
        try {
            SampleDataGenerator.generateData();
            Assert.fail('Expected SampleDataGeneratorException');
        } catch (Exception e) {
            Assert.isInstanceOfType(
                e,
                SampleDataGenerator.SampleDataGeneratorException.class
            );
            Assert.isTrue(e.getMessage().contains('Failed to find contact'));
        }
        Test.stopTest();
    }

    @isTest
    static void sampleBookingBatch_works() {
        List<Contact> contacts = getMockContacts(20);
        insert contacts;
        List<Experience__c> experiences = getMockExperiences(1);
        insert experiences;
        List<Session__c> sessions = getMockSessions(experiences, 3);
        insert sessions;

        Test.startTest();
        SampleBookingBatch batch = new SampleBookingBatch(
            experiences,
            sessions,
            contacts
        );
        Database.executeBatch(batch);
        Test.stopTest();

        List<Booking__c> bookings = [
            SELECT Session__c, Number_of_Guests__c
            FROM Booking__c
        ];
        Map<Id, Decimal> sessionGuests = new Map<Id, Decimal>();
        for (Booking__c booking : bookings) {
            Decimal guestCount = sessionGuests.get(booking.Session__c);
            if (guestCount == null) {
                guestCount = 0;
            }
            guestCount += booking.Number_of_Guests__c;
            sessionGuests.put(booking.Session__c, guestCount);
        }
        Assert.areEqual(
            sessions.size(),
            sessionGuests.size(),
            'Expected bookings to cover all sessions'
        );
        for (Id sessionId : sessionGuests.keySet()) {
            Decimal guestCount = sessionGuests.get(sessionId);
            Assert.isTrue(
                guestCount >=
                SESSION_CAPACITY * SampleBookingBatch.MIN_SESSION_FILL_PERCENT,
                'Expected guests count to be greater or equal to min fill target'
            );
            Assert.isTrue(
                guestCount <=
                SESSION_CAPACITY * SampleBookingBatch.MAX_SESSION_FILL_PERCENT,
                'Expected guests count to be lower or equal to max fill target'
            );
        }
    }

    private static List<Contact> getMockContacts(Integer count) {
        List<Contact> contacts = new List<Contact>();
        for (Integer i = 0; i < count; i++) {
            contacts.add(
                new Contact(FirstName = 'fn' + i, LastName = 'ln' + i)
            );
        }
        return contacts;
    }

    private static List<Experience__c> getMockExperiences(Integer count) {
        List<Experience__c> experiences = new List<Experience__c>();
        for (Integer i = 0; i < count; i++) {
            Experience__c experience = new Experience__c(Name = 'mockExp');
            experience.Name = 'activity' + i;
            experience.Activity_Level__c = 'Low';
            experience.Capacity__c = 100;
            experience.Default_Start_Time__c = Time.newInstance(0, 0, 0, 0);
            experience.Description__c = 'desc';
            experience.Duration_Hours__c = 1;
            experience.Location__c = 'Ocean Cruise';
            experience.Picture_URL__c = 'https://salesforce.com';
            experience.Price__c = 0;
            experience.Type__c = 'Nightlife & Entertainment';
            experiences.add(experience);
        }
        return experiences;
    }

    private static List<Session__c> getMockSessions(
        List<Experience__c> experiences,
        Integer count
    ) {
        List<Session__c> sessions = new List<Session__c>();
        for (Experience__c experience : experiences) {
            for (Integer i = 0; i < count; i++) {
                Session__c session = new Session__c();
                session.Date__c = Date.today();
                session.Experience__c = experience.Id;
                session.Start_Time__c = Time.newInstance(0, 0, 0, 0);
                sessions.add(session);
            }
        }
        return sessions;
    }
}