force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description
    >The Booking custom object manages reservations for guest activities, linking guests to their chosen experiences and tracking details like booking status and guest information, enabling efficient occupancy and capacity management.</description>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{00000000}</displayFormat>
        <label>Booking Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cc-base-app/main/default/objects/Booking__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description
    >The date of the booked experience, aiding in schedule planning.</description>
    <formula>Session__r.Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <description
    >Connects the booking to a specific session of an activity, detailing when and where it occurs.</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cc-base-app/main/default/objects/Booking__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description
    >The starting time of the experience, helping guests plan their day.</description>
    <formula>Session__r.Start_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

cc-base-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description
    >The Experiences custom object is designed to comprehensively track and manage all guest-related activities and services offered by the resort, such as recreational activities, golf outings, spa treatments, and other special events.</description>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <description
    >Defines the maximum number of participants that can be accommodated in a single session of the experience, ensuring optimal guest enjoyment and safety.</description>
    <label>Capacity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cc-base-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <description
    >The Session custom object tracks specific sessions of activities offered by the resort, detailing timing, location, and capacity, to manage bookings and optimize guest participation efficiently.</description>
    <label>Experience Session</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Session Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experience Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <formula>Experience__r.Capacity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description
    >Specifies the date on which the experience instance takes place, facilitating scheduling and planning for both the resort and the guests.</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >The parent experience that this object is scheduled based on.</description>
    <label>Experience</label>
    <referenceTo>Experience__c</referenceTo>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

cc-base-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description
    >Indicates the beginning time of the experience instance, helping guests plan their day around scheduled activities.</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

cc-base-app/main/setup/classes/SampleDataGenerator.cls
public with sharing class SampleDataGenerator {
    private static final List<Time> SESSION_TIMES = new List<Time>{
        Time.newInstance(9, 0, 0, 0),
        Time.newInstance(13, 30, 0, 0)
    };

    private static final Integer SESSION_BATCH_SIZE = 500;
    @TestVisible
    private static final Integer FUTURE_DAYS_COVERED = 4;
    @TestVisible
    private static final Integer PAST_DAYS_COVERED = 1;

    @AuraEnabled
    public static Id generateData() {
        // Remove current sessions and bookings
        delete [SELECT Id FROM Booking__c];
        delete [SELECT Id FROM Session__c];

        // Get existing contacts and experiences
        List<Contact> contacts = [SELECT Id FROM Contact];
        List<Experience__c> experiences = [
            SELECT Id, Capacity__c
            FROM Experience__c
        ];
        // Check for exisisting data
        if (contacts.size() == 0 || experiences.size() == 0) {
            throw new SampleDataGeneratorException(
                'Failed to find contact and/org experience records. Did you load the sample data plan first?'
            );
        }

        // Generate new sessions
        List<Session__c> sessions = generateSessions(experiences);
        insert as user sessions;

        // Generate bookings in batch to avoid hitting DML limits
        SampleBookingBatch sampleBooking = new SampleBookingBatch(
            experiences,
            sessions,
            contacts
        );
        Id batchProcessId = Database.executeBatch(
            sampleBooking,
            SESSION_BATCH_SIZE
        );
        return batchProcessId;
    }

    private static Integer getRandomInteger(Integer min, Integer max) {
        Double rand = min + (Math.random() * (max - min));
        return Integer.valueOf(rand);
    }

    private static List<Session__c> generateSessions(
        List<Experience__c> experiences
    ) {
        List<Session__c> sessions = new List<Session__c>();
        for (Experience__c experience : experiences) {
            Date sessionDate = Date.today().addDays(0 - PAST_DAYS_COVERED);
            for (
                Integer d = 0; d < PAST_DAYS_COVERED + FUTURE_DAYS_COVERED; d++
            ) {
                sessionDate = sessionDate.addDays(1);
                Integer sessionCountForThisDay = getRandomInteger(
                    1,
                    SESSION_TIMES.size()
                );
                for (Integer t = 0; t < sessionCountForThisDay; t++) {
                    Time sessionTime = SESSION_TIMES[t];
                    Session__c session = new Session__c();
                    session.Date__c = sessionDate;
                    session.Experience__c = experience.Id;
                    session.Start_Time__c = sessionTime;
                    sessions.add(session);
                }
            }
        }
        return sessions;
    }

    public class SampleDataGeneratorException extends Exception {
    }
}