force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description
    >The Booking custom object manages reservations for guest activities, linking guests to their chosen experiences and tracking details like booking status and guest information, enabling efficient occupancy and capacity management.</description>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{00000000}</displayFormat>
        <label>Booking Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cc-base-app/main/default/objects/Booking__c/fields/Number_of_Guests__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Guests__c</fullName>
    <description
    >Specifies how many guests are included in the booking, ensuring appropriate accommodation.</description>
    <label>Number of Guests</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <description
    >Connects the booking to a specific session of an activity, detailing when and where it occurs.</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cc-base-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description
    >The Experiences custom object is designed to comprehensively track and manage all guest-related activities and services offered by the resort, such as recreational activities, golf outings, spa treatments, and other special events.</description>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <description
    >Defines the maximum number of participants that can be accommodated in a single session of the experience, ensuring optimal guest enjoyment and safety.</description>
    <label>Capacity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cc-base-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <description
    >The Session custom object tracks specific sessions of activities offered by the resort, detailing timing, location, and capacity, to manage bookings and optimize guest participation efficiently.</description>
    <label>Experience Session</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Session Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experience Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <formula>Experience__r.Capacity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >The parent experience that this object is scheduled based on.</description>
    <label>Experience</label>
    <referenceTo>Experience__c</referenceTo>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/setup/classes/SampleBookingBatch.cls
public with sharing class SampleBookingBatch implements Database.Batchable<Session__c> {
    private List<Session__c> sessions;
    private List<Contact> contacts;
    private Map<Id, Integer> xpCapacities;

    @TestVisible
    private static final Decimal MIN_SESSION_FILL_PERCENT = 0.40;
    @TestVisible
    private static final Decimal MAX_SESSION_FILL_PERCENT = 0.75;

    public SampleBookingBatch(
        List<Experience__c> experiences,
        List<Session__c> sessions,
        List<Contact> contacts
    ) {
        this.sessions = sessions;
        this.contacts = contacts;
        // Get experience guest capacities
        this.xpCapacities = new Map<Id, Integer>();
        for (Experience__c experience : experiences) {
            this.xpCapacities.put(
                experience.Id,
                Integer.valueOf(experience.Capacity__c)
            );
        }
    }

    public Iterable<Session__c> start(Database.BatchableContext bc) {
        return this.sessions;
    }

    public void execute(
        Database.BatchableContext bc,
        List<Session__c> sessions
    ) {
        List<Booking__c> bookings = new List<Booking__c>();
        // Fill sessions
        for (Session__c session : sessions) {
            // Get session capacity based on experience
            Integer capacity = this.xpCapacities.get(session.Experience__c);

            // Calculate the booking target as a random value between 70% and 85% of capacity.
            Double targetPercentage =
                MIN_SESSION_FILL_PERCENT +
                (Math.random() *
                (MAX_SESSION_FILL_PERCENT - MIN_SESSION_FILL_PERCENT));
            Integer slotsToFill = Integer.valueOf(
                Math.ceil(capacity * targetPercentage)
            );

            // Fill session with random contacts
            while (slotsToFill > 0) {
                // Get random contact
                Integer randomIndex = Math.floor(
                        Math.random() * this.contacts.size()
                    )
                    .intValue();
                Contact contact = this.contacts.get(randomIndex);
                // Dynamically adjust the number of guests per booking based on remaining slots to fill and randomization
                Integer maxGuestsThisBooking = Math.min(6, slotsToFill);
                Integer numberOfGuests =
                    Math.floor(Math.random() * maxGuestsThisBooking)
                        .intValue() + 1;
                slotsToFill -= numberOfGuests;
                // Prepare booking record
                Booking__c booking = new Booking__c(
                    Contact__c = contact.Id,
                    Session__c = session.Id,
                    Number_of_Guests__c = numberOfGuests
                );
                bookings.add(booking);
            }
        }
        insert bookings;
    }

    public void finish(Database.BatchableContext bc) {
    }
}