force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description
    >The Booking custom object manages reservations for guest activities, linking guests to their chosen experiences and tracking details like booking status and guest information, enabling efficient occupancy and capacity management.</description>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{00000000}</displayFormat>
        <label>Booking Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cc-base-app/main/default/objects/Booking__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description
    >The date of the booked experience, aiding in schedule planning.</description>
    <formula>Session__r.Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date</label>
    <type>Date</type>
</CustomField>

cc-base-app/main/default/objects/Booking__c/fields/Number_of_Guests__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Guests__c</fullName>
    <description
    >Specifies how many guests are included in the booking, ensuring appropriate accommodation.</description>
    <label>Number of Guests</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <description
    >Connects the booking to a specific session of an activity, detailing when and where it occurs.</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cc-base-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <description
    >The Session custom object tracks specific sessions of activities offered by the resort, detailing timing, location, and capacity, to manage bookings and optimize guest participation efficiently.</description>
    <label>Experience Session</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Session Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experience Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description
    >Specifies the date on which the experience instance takes place, facilitating scheduling and planning for both the resort and the guests.</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/setup/classes/DemoSetup.cls
public with sharing class DemoSetup {
    /**
     * Shifts all session experience dates to be arround demo date
     * Cleans bookings for Sofia
     */
    public static void run() {
        shiftExperienceSessionDates();
        cleanSofiasSessionBookings();
    }

    private static void shiftExperienceSessionDates() {
        AggregateResult[] results = [
            SELECT MIN(Date__c) minDate, MAX(Date__c) maxDate
            FROM Session__c
        ];
        Date minDate = (Date) results[0].get('minDate');
        Date maxDate = (Date) results[0].get('maxDate');
        if (minDate == null || maxDate == null) {
            return;
        }
        System.debug(
            'Session date range: ' +
                String.valueOf(minDate) +
                ' to ' +
                String.valueOf(maxDate)
        );

        Integer rangeSpanDays = minDate.daysBetween(maxDate);
        Date midDate = minDate.addDays(rangeSpanDays / 2);
        Integer offsetDays = midDate.daysBetween(Date.today());
        System.debug(
            'Offseting all dates by ' +
                offsetDays +
                ' days from ' +
                String.valueOf(midDate)
        );

        if (offsetDays != 0) {
            List<Session__c> sessions = [SELECT Id, Date__c FROM Session__c];
            for (Session__c session : sessions) {
                session.Date__c = session.Date__c.addDays(offsetDays);
            }
            System.debug('Updating ' + sessions.size() + ' sessions');
            update sessions;
        }
    }

    private static void cleanSofiasSessionBookings() {
        System.debug('Adjusting Sofia\'s bookings');
        // Find Sofia
        Contact sofia = [
            SELECT Id
            FROM Contact
            WHERE Name = 'Sofia Rodriguez'
            LIMIT 1
        ];
        // Remove Sofia's bookings
        delete [
            SELECT Id
            FROM Booking__c
            WHERE Contact__c = :sofia.Id
        ];
        // Add past bookings from 2 previous days
        for (Integer i = 0; i < 2; i++) {
            Date targetDate = Date.today().addDays(-i - 1);
            List<Session__c> sessions = [
                SELECT Id
                FROM Session__c
                WHERE Date__c = :targetDate
                LIMIT 100
            ];
            Session__c session = sessions[
                Integer.valueof((Math.random() * sessions.size()))
            ];
            insert new Booking__c(
                Contact__c = sofia.Id,
                Session__c = session.Id,
                Number_of_Guests__c = 1
            );
        }
    }
}