force-app/main/default/objects/Contact/fields/Interest1__c.field-meta.xml
<CustomField>
    <fullName>Interest1__c</fullName>
    <label>Interest 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cc-base-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description
    >The Experiences custom object is designed to comprehensively track and manage all guest-related activities and services offered by the resort, such as recreational activities, golf outings, spa treatments, and other special events.</description>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description
    >The Type field categorizes experiences into specific activities like &quot;Tennis &amp; Pickleball,&quot; &quot;Swimming Pools,&quot; and &quot;Beaches &amp; Snorkeling,&quot; helping guests easily find and book preferred activities, and aiding resort organization.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adventure Activities</fullName>
            </value>
            <value>
                <fullName>Beaches &amp; Snorkeling</fullName>
            </value>
            <value>
                <fullName>Cultural Tours &amp; Workshops</fullName>
            </value>
            <value>
                <fullName>Dining Experiences</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids&apos; Activities</fullName>
            </value>
            <value>
                <fullName>Fitness &amp; Exercise</fullName>
            </value>
            <value>
                <fullName>Golf</fullName>
            </value>
            <value>
                <fullName>Nature &amp; Eco Tours</fullName>
            </value>
            <value>
                <fullName>Nightlife &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Relaxation &amp; Quiet Zones</fullName>
            </value>
            <value>
                <fullName>Spa &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Swimming Pools</fullName>
            </value>
            <value>
                <fullName>Tennis &amp; Pickleball</fullName>
            </value>
            <value>
                <fullName>Water Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cc-base-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <description
    >The Session custom object tracks specific sessions of activities offered by the resort, detailing timing, location, and capacity, to manage bookings and optimize guest participation efficiently.</description>
    <label>Experience Session</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Session Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experience Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description
    >Specifies the date on which the experience instance takes place, facilitating scheduling and planning for both the resort and the guests.</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
    >The parent experience that this object is scheduled based on.</description>
    <label>Experience</label>
    <referenceTo>Experience__c</referenceTo>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

cc-base-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description
    >Indicates the beginning time of the experience instance, helping guests plan their day around scheduled activities.</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/ExperienceControllerTest.cls
@isTest
private class ExperienceControllerTest {
    private static final Datetime REFERENCE_DATETIME = Datetime.newInstance(
        2024,
        7,
        19,
        11,
        0,
        0
    );

    @testSetup
    static void setup() {
        List<Experience__c> experiences = new List<Experience__c>{
            new Experience__c(
                Name = 'xp1',
                Type__c = 'Cultural Tours & Workshops'
            ),
            new Experience__c(
                Name = 'xp2',
                Type__c = 'Nightlife & Entertainment'
            )
        };
        insert experiences;

        Datetime dayBefore = REFERENCE_DATETIME.addDays(-1);
        Datetime dayAfter = REFERENCE_DATETIME.addDays(1);

        List<Session__c> allSessions = new List<Session__c>{
            new Session__c(
                Experience__c = experiences[0].Id,
                Date__c = dayBefore.date(),
                Start_Time__c = dayBefore.time()
            ),
            new Session__c(
                Experience__c = experiences[0].Id,
                Date__c = REFERENCE_DATETIME.date(),
                Start_Time__c = REFERENCE_DATETIME.time()
            ),
            new Session__c(
                Experience__c = experiences[0].Id,
                Date__c = dayAfter.date(),
                Start_Time__c = dayAfter.time()
            ),
            new Session__c(
                Experience__c = experiences[0].Id,
                Date__c = REFERENCE_DATETIME.date(),
                Start_Time__c = REFERENCE_DATETIME.addHours(-2).time()
            ),
            new Session__c(
                Experience__c = experiences[1].Id,
                Date__c = REFERENCE_DATETIME.date(),
                Start_Time__c = REFERENCE_DATETIME.addHours(-2).time()
            ),
            new Session__c(
                Experience__c = experiences[1].Id,
                Date__c = Date.today(),
                Start_Time__c = REFERENCE_DATETIME.addHours(-2).time()
            )
        };
        insert allSessions;
    }

    @isTest
    static void getExperienceSessionsForDate_works() {
        Experience__c experience = [
            SELECT Id
            FROM Experience__c
            WHERE Name = 'xp1'
        ];
        List<Session__c> allSessions = [SELECT Id FROM Session__c];

        Test.startTest();
        List<Session__c> todaySessions = ExperienceController.getExperienceSessionsForDate(
            experience.Id,
            REFERENCE_DATETIME.getTime()
        );
        Test.stopTest();

        Assert.areEqual(2, todaySessions.size());
        Assert.areEqual(
            allSessions[3].Id,
            todaySessions[0].Id,
            'Sessions are not ordered by start time'
        );
        Assert.areEqual(allSessions[1].Id, todaySessions[1].Id);
    }

    @isTest
    static void getSessions_works() {
        Contact contact = new Contact(
            FirstName = 'fn',
            LastName = 'ln',
            Interest1__c = 'Nightlife & Entertainment'
        );
        insert contact;

        Test.startTest();
        List<Session__c> sessions = ExperienceController.getSessions(contact);
        Test.stopTest();

        Assert.areEqual(1, sessions.size());
    }
}